# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{guardian-content}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["frankieroberto"]
  s.date = %q{2010-05-19}
  s.description = %q{A library for the Guardian Content API}
  s.email = %q{frankie@frankieroberto.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "guardian-content.gemspec",
     "lib/guardian-content.rb",
     "lib/guardian-content/content.rb",
     "lib/guardian-content/contributor.rb",
     "lib/guardian-content/extensions.rb",
     "lib/guardian-content/keyword.rb",
     "lib/guardian-content/section.rb",
     "lib/guardian-content/tag.rb",
     "test/helper.rb",
     "test/test_guardian-content.rb",
     "test/test_search_content.rb",
     "test/test_section.rb",
     "test/test_tag_search.rb"
  ]
  s.homepage = %q{http://github.com/guardian-openplatform/contentapi-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Queries the Guardian Content API}
  s.test_files = [
    "test/helper.rb",
     "test/test_guardian-content.rb",
     "test/test_search_content.rb",
     "test/test_section.rb",
     "test/test_tag_search.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
    else
      s.add_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 2.10.3"])
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
  end
end

